[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "MIT", "ISC", "Unicode-3.0"]

[advisories]
ignore = [
  { id = "RUSTSEC-2024-0436", reason = "there aren't known vulnerabilities, we only use it in a dev-dependency, and we don't actually use the codepaths that use it" },
]
